SELECT TOP 1 j.JUGA_DNI, j.JUGA_APELLIDO, j.JUGA_NOMBRES, j.JUGA_PESO, e.EQUI_NOMBRE, (SELECT COUNT(*)+1 FROM PARTIDO partido2 WHERE partido2.PART_FECHA_HORA < p.PART_FECHA_HORA AND partido2.PART_FECHA_TORNEO = p.PART_FECHA_TORNEO AND partido2.PART_TORNEO = p.PART_TORNEO) 'NRO PARTIDO'
FROM EQUIPO e
JOIN PARTIDO p on (p.PART_VISITANTE = e.EQUI_CODIGO OR p.PART_LOCAL = e.EQUI_CODIGO) AND p.PART_FECHA_TORNEO = 1
JOIN JUGADOR_PARTIDO jp ON p.PART_CODIGO = jp.JUPA_PARTIDO AND e.EQUI_CODIGO = jp.JUPA_EQUIPO
JOIN JUGADOR j ON j.JUGA_DNI = jp.JUPA_JUGADOR
JOIN TORNEO t on p.PART_TORNEO = t.TORN_CODIGO AND t.TORN_DIVISION = 'B'
ORDER BY j.JUGA_PESO DESC
