SELECT dir.DITE_DNI DNI, dir.DITE_NOMBRES NOMBRES, dir.DITE_APELLIDO APELLIDO, dir.DITE_EDAD EDAD, equi.EQUI_NOMBRE
FROM DIRECTOR_TECNICO dir
JOIN EQUIPO equi ON equi.EQUI_DT = dir.DITE_DNI
JOIN EQUIPO_JUGADOR ej ON ej.EQJU_EQUIPO = equi.EQUI_CODIGO AND ej.EQJU_JUGADOR = dir.DITE_DNI
ORDER BY dir.DITE_APELLIDO