SELECT j.JUGA_DNI, j.JUGA_APELLIDO, j.JUGA_NOMBRES, pos.POSI_DETALLE
FROM JUGADOR j
JOIN POSICION pos ON pos.POSI_CODIGO = j.JUGA_POSICION_FAVORITA
JOIN EQUIPO_JUGADOR ej ON ej.EQJU_JUGADOR = j.JUGA_DNI
JOIN EQUIPO e ON e.EQUI_CODIGO = ej.EQJU_EQUIPO AND e.EQUI_NOMBRE = 'NEWELLS'
