CREATE FUNCTION POSICION_MAS_JUGADA (@DNI INT)
RETURNS CHAR(3) AS
BEGIN

DECLARE @POSICION CHAR(3)

SET @POSICION = (SELECT TOP 1 JP.JUPA_POSICION 
				 FROM JUGADOR_PARTIDO JP
				 WHERE JP.JUPA_JUGADOR = @DNI
				 GROUP BY JP.JUPA_POSICION
				 ORDER BY COUNT(*) DESC
				  )
			
RETURN @POSICION

END
