/* 14) DADO UN JUGADOR DEVUELVE LA CANTIDAD DE VECES QUE SALIO CAMPEON, SE USA LA VISTA "TABLA DE POSICIONES" */
CREATE FUNCTION VECES_CAMPEON_JUGADOR(@DNI VARCHAR(8))
RETURNS INT AS 
BEGIN

DECLARE @VECES INT

SET @VECES = (SELECT COUNT(*)

FROM dbo.TABLA_POSICIONES TP
	 INNER JOIN EQUIPO_JUGADOR EJ ON EJ.EQJU_EQUIPO = TP.TAPO_EQUIPO
WHERE EJ.EQJU_JUGADOR = @DNI AND TP.TAPO_POSICION = 1)


IF @VECES IS NULL
SET @VECES = 0


RETURN @VECES


END
