
/*LA ESTRATEGIA ES BUSCAR LOS PARTIDOS DONDE EL EQUIPO QUE EMPEZO GANANDO, TERMINO PERDIENDO, PARA ESO,
SE BUSCA QUIEN HIZO EL PRIMER GOL Y LUEGO PERDIO*/

SELECT EL.EQUI_NOMBRE AS EQUIPO_LOCAL, EV.EQUI_NOMBRE AS EQUIPO_VISITANTE, (SELECT COUNT(DP.DEPA_ACCION)
										FROM DETALLE_PARTIDO DP JOIN TIPO_ACCION TA ON DP.DEPA_ACCION = TA.TIAC_CODIGO
										WHERE DP.DEPA_PARTIDO = P.PART_CODIGO AND 
											((DP.DEPA_EQUIPO = EL.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL') OR 
											(DP.DEPA_EQUIPO = EV.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL EN CONTRA'))
											) AS GOLES_LOCAL,
										(SELECT COUNT(DP.DEPA_ACCION)
										FROM DETALLE_PARTIDO DP JOIN TIPO_ACCION TA ON DP.DEPA_ACCION = TA.TIAC_CODIGO
										WHERE DP.DEPA_PARTIDO = P.PART_CODIGO AND 
											((DP.DEPA_EQUIPO = EV.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL') OR 
											(DP.DEPA_EQUIPO = EL.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL EN CONTRA'))
											) AS GOLES_VISITANTE
FROM PARTIDO P JOIN DETALLE_PARTIDO DEPA ON P.PART_CODIGO = DEPA.DEPA_PARTIDO
				JOIN EQUIPO EL ON EL.EQUI_CODIGO = P.PART_LOCAL
				JOIN EQUIPO EV ON EV.EQUI_CODIGO = P.PART_VISITANTE		
WHERE (((SELECT MIN(DP.DEPA_MINUTO)
		FROM DETALLE_PARTIDO DP JOIN TIPO_ACCION TA ON DP.DEPA_ACCION = TA.TIAC_CODIGO
		WHERE DP.DEPA_PARTIDO = P.PART_CODIGO AND 
			((DP.DEPA_EQUIPO = EL.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL') OR 
			(DP.DEPA_EQUIPO = EV.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL EN CONTRA')))
		<
		(SELECT MIN(DP.DEPA_MINUTO)
		FROM DETALLE_PARTIDO DP JOIN TIPO_ACCION TA ON DP.DEPA_ACCION = TA.TIAC_CODIGO
		WHERE DP.DEPA_PARTIDO = P.PART_CODIGO AND 
			((DP.DEPA_EQUIPO = EV.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL') OR 
			(DP.DEPA_EQUIPO = EL.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL EN CONTRA'))))
		AND 	
		((SELECT COUNT(DP.DEPA_ACCION)
		FROM DETALLE_PARTIDO DP JOIN TIPO_ACCION TA ON DP.DEPA_ACCION = TA.TIAC_CODIGO
		WHERE DP.DEPA_PARTIDO = P.PART_CODIGO AND 
			((DP.DEPA_EQUIPO = EL.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL') OR 
			(DP.DEPA_EQUIPO = EV.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL EN CONTRA'))
			) <
		(SELECT COUNT(DP.DEPA_ACCION)
		FROM DETALLE_PARTIDO DP JOIN TIPO_ACCION TA ON DP.DEPA_ACCION = TA.TIAC_CODIGO
		WHERE DP.DEPA_PARTIDO = P.PART_CODIGO AND 
			((DP.DEPA_EQUIPO = EV.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL') OR 
			(DP.DEPA_EQUIPO = EL.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL EN CONTRA'))
			)))					
		OR
		(((SELECT MIN(DP.DEPA_MINUTO)
		FROM DETALLE_PARTIDO DP JOIN TIPO_ACCION TA ON DP.DEPA_ACCION = TA.TIAC_CODIGO
		WHERE DP.DEPA_PARTIDO = P.PART_CODIGO AND 
			((DP.DEPA_EQUIPO = EL.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL') OR 
			(DP.DEPA_EQUIPO = EV.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL EN CONTRA')))
		>
		(SELECT MIN(DP.DEPA_MINUTO)
		FROM DETALLE_PARTIDO DP JOIN TIPO_ACCION TA ON DP.DEPA_ACCION = TA.TIAC_CODIGO
		WHERE DP.DEPA_PARTIDO = P.PART_CODIGO AND 
			((DP.DEPA_EQUIPO = EV.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL') OR 
			(DP.DEPA_EQUIPO = EL.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL EN CONTRA'))))
		AND 	
		((SELECT COUNT(DP.DEPA_ACCION)
		FROM DETALLE_PARTIDO DP JOIN TIPO_ACCION TA ON DP.DEPA_ACCION = TA.TIAC_CODIGO
		WHERE DP.DEPA_PARTIDO = P.PART_CODIGO AND 
			((DP.DEPA_EQUIPO = EL.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL') OR 
			(DP.DEPA_EQUIPO = EV.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL EN CONTRA'))
			) >
		(SELECT COUNT(DP.DEPA_ACCION)
		FROM DETALLE_PARTIDO DP JOIN TIPO_ACCION TA ON DP.DEPA_ACCION = TA.TIAC_CODIGO
		WHERE DP.DEPA_PARTIDO = P.PART_CODIGO AND 
			((DP.DEPA_EQUIPO = EV.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL') OR 
			(DP.DEPA_EQUIPO = EL.EQUI_CODIGO AND TA.TIAC_DETALLE = 'GOL EN CONTRA'))
			)))		  
GROUP BY P.PART_FECHA_HORA, EL.EQUI_NOMBRE, EV.EQUI_NOMBRE, P.PART_CODIGO, EL.EQUI_CODIGO, EV.EQUI_CODIGO
ORDER BY P.PART_FECHA_HORA