CREATE TRIGGER fecha_fuera_de_termino
ON PARTIDO
INSTEAD OF INSERT
AS BEGIN

	IF(((SELECT PART_FECHA_HORA FROM inserted) 
		> (SELECT T.TORN_FECHA_FIN FROM TORNEO T JOIN inserted ON T.TORN_CODIGO = PART_TORNEO)
		OR
		(SELECT PART_FECHA_HORA FROM inserted) 
		< (SELECT T.TORN_FECHA_INICIO FROM TORNEO T JOIN inserted ON T.TORN_CODIGO = PART_TORNEO))
		AND ((SELECT PART_FECHA_TORNEO FROM inserted) 
		<> (SELECT T.TORN_CANTIDAD_FECHAS FROM TORNEO T JOIN inserted ON T.TORN_CODIGO = PART_TORNEO)))
		BEGIN
			PRINT('ERROR! LA FECHA ESTA FUERA DE RANGO!')
	END
	ELSE BEGIN
			INSERT INTO PARTIDO (PART_FECHA_HORA, PART_DURACION, PART_ADICIONAL, PART_LOCAL, PART_VISITANTE,
								PART_ARBITRO, PART_TORNEO, PART_FECHA_TORNEO, PART_GOLES_LOCAL, PART_GOLES_VISITANTE, PART_CALIF_ARBITRO)
					
					SELECT PART_FECHA_HORA, PART_DURACION, PART_ADICIONAL, PART_LOCAL, PART_VISITANTE,
								PART_ARBITRO, PART_TORNEO, PART_FECHA_TORNEO, PART_GOLES_LOCAL, PART_GOLES_VISITANTE, PART_CALIF_ARBITRO
					FROM inserted
	END
END
		 
														