CREATE VIEW PARTIDO_PUNTOS (PAPU_TORNEO, PAPU_PARTIDO, PAPU_EQUIPO, PAPU_GOL_FAVOR, PAPU_GOL_CONTRA, PAPU_DIFERENCIA_GOLES, PAPU_PUNTOS) AS
(SELECT PART_TORNEO, PART_CODIGO, PART_VISITANTE, COUNT(V.DEPA_CODIGO), COUNT(L.DEPA_CODIGO),  COUNT(V.DEPA_CODIGO) - COUNT(L.DEPA_CODIGO),
		(CASE  WHEN PART_DURACION IS NULL THEN NULL
			WHEN COUNT(V.DEPA_CODIGO) = COUNT(L.DEPA_CODIGO) THEN 1
			WHEN COUNT(V.DEPA_CODIGO) > COUNT(L.DEPA_CODIGO) THEN 3
			ELSE 0 END)
FROM PARTIDO
JOIN EQUIPO ON EQUI_CODIGO = PART_VISITANTE
LEFT JOIN DETALLE_PARTIDO V ON (V.DEPA_PARTIDO = PART_CODIGO) AND ((V.DEPA_ACCION = 1 AND PART_VISITANTE = V.DEPA_EQUIPO) OR (V.DEPA_ACCION = 10 AND PART_LOCAL = V.DEPA_EQUIPO))
LEFT JOIN DETALLE_PARTIDO L ON (L.DEPA_PARTIDO = PART_CODIGO) AND ((L.DEPA_ACCION = 10 AND PART_VISITANTE = L.DEPA_EQUIPO) OR (L.DEPA_ACCION = 1 AND PART_LOCAL = L.DEPA_EQUIPO))

GROUP BY PART_TORNEO, PART_CODIGO, PART_VISITANTE, EQUI_NOMBRE, PART_DURACION

UNION

SELECT PART_TORNEO, PART_CODIGO, PART_LOCAL, COUNT(L.DEPA_CODIGO), COUNT(V.DEPA_CODIGO), COUNT(L.DEPA_CODIGO) - COUNT(V.DEPA_CODIGO),
		(CASE WHEN PART_DURACION IS NULL THEN NULL
			WHEN COUNT(V.DEPA_CODIGO) = COUNT(L.DEPA_CODIGO) THEN 1
			WHEN COUNT(V.DEPA_CODIGO) < COUNT(L.DEPA_CODIGO) THEN 3
			ELSE 0 END)
FROM PARTIDO
JOIN EQUIPO ON EQUI_CODIGO = PART_LOCAL
LEFT JOIN DETALLE_PARTIDO V ON (V.DEPA_PARTIDO = PART_CODIGO) AND ((V.DEPA_ACCION = 1 AND PART_VISITANTE = V.DEPA_EQUIPO) OR (V.DEPA_ACCION = 10 AND PART_LOCAL = V.DEPA_EQUIPO))
LEFT JOIN DETALLE_PARTIDO L ON (L.DEPA_PARTIDO = PART_CODIGO) AND ((L.DEPA_ACCION = 10 AND PART_VISITANTE = L.DEPA_EQUIPO) OR (L.DEPA_ACCION = 1 AND PART_LOCAL = L.DEPA_EQUIPO))

GROUP BY PART_TORNEO, PART_CODIGO, PART_LOCAL, EQUI_NOMBRE, PART_DURACION)