CREATE TRIGGER actualizoPromedio
on JUGADOR_PARTIDO
FOR insert,UPDATE, delete
AS
BEGIN
	UPDATE JUGADOR
		SET JUGA_PROMEDIO = (
			SELECT AVG(JUPA_CALIFICACION)
			FROM JUGADOR_PARTIDO
			WHERE JUPA_JUGADOR = JUGA_DNI)
	WHERE JUGA_DNI IN (SELECT JUPA_JUGADOR FROM INSERTED
						union
						SELECT JUPA_JUGADOR FROM DELETED)	
END
