SELECT P.PART_CODIGO, E1.EQUI_NOMBRE AS LOCAL, E2.EQUI_NOMBRE AS VISITANTE,
SUM(CASE WHEN ((DP.DEPA_ACCION=1 AND DP.DEPA_EQUIPO=P.PART_LOCAL) OR (DP.DEPA_ACCION=10 AND DP.DEPA_EQUIPO=P.PART_VISITANTE))
 THEN 1 ELSE 0 END) AS golesLocal,
SUM(CASE WHEN ((DP.DEPA_ACCION=1 AND DP.DEPA_EQUIPO=P.PART_VISITANTE) OR (DP.DEPA_ACCION=10 AND DP.DEPA_EQUIPO=P.PART_LOCAL))
 THEN 1 ELSE 0 END) AS golesVisitante
FROM PARTIDO P
JOIN EQUIPO E1 ON E1.EQUI_CODIGO = P.PART_LOCAL
JOIN EQUIPO E2 ON E2.EQUI_CODIGO = P.PART_VISITANTE
JOIN DETALLE_PARTIDO DP ON DP.DEPA_PARTIDO = P.PART_CODIGO
GROUP BY P.PART_CODIGO, E1.EQUI_NOMBRE, E2.EQUI_NOMBRE