SELECT A.ARBI_APELLIDO, A.ARBI_NOMBRES, COUNT(P.PART_ARBITRO)
FROM ARBITRO A
JOIN PARTIDO P ON P.PART_ARBITRO = A.ARBI_DNI
WHERE (
		SELECT COUNT(*)
		FROM PARTIDO P 
		JOIN EQUIPO E ON (P.PART_LOCAL = E.EQUI_CODIGO OR P.PART_VISITANTE = E.EQUI_CODIGO)
		WHERE (E.EQUI_NOMBRE ='SAN LORENZO') AND P.PART_ARBITRO= A.ARBI_DNI
	) > 1 AND (P.PART_DURACION IS NOT NULL)
GROUP BY A.ARBI_APELLIDO, A.ARBI_NOMBRES
ORDER BY A.ARBI_APELLIDO

/*SELECCIONO CANT DE ENCUENTROS DIRIGIDOS (DURACION IS NOT NULL)
DE LOS ARBITROS QUE HAYAN DIRIGIDO O ESTEN ASIGNADOS A SAN LORENZO
2 O MAS VECES*/

