SELECT TOP 1 (J.JUGA_PESO), J.JUGA_DNI, J.JUGA_APELLIDO, J.JUGA_NOMBRES,
E.EQUI_NOMBRE, P.PART_CODIGO
FROM JUGADOR J
JOIN EQUIPO_JUGADOR EJ ON EJ.EQJU_JUGADOR = J.JUGA_DNI
JOIN EQUIPO E ON E.EQUI_CODIGO = EJ.EQJU_EQUIPO
JOIN JUGADOR_PARTIDO JP ON JP.JUPA_JUGADOR = J.JUGA_DNI
JOIN PARTIDO P ON P.PART_CODIGO = JP.JUPA_PARTIDO

WHERE P.PART_FECHA_TORNEO=1 AND E.EQUI_DIVISION='B'
ORDER BY J.JUGA_PESO DESC