SELECT D.DITE_DNI, D.DITE_NOMBRES, D.DITE_APELLIDO, D.DITE_EDAD, E.EQUI_NOMBRE
FROM DIRECTOR_TECNICO D
JOIN EQUIPO E ON E.EQUI_DT = D.DITE_DNI
JOIN EQUIPO_JUGADOR EJ ON EJ.EQJU_EQUIPO = E.EQUI_CODIGO 
WHERE EJ.EQJU_JUGADOR = D.DITE_DNI
ORDER BY D.DITE_APELLIDO ASC