SELECT J.JUGA_NOMBRES, J.JUGA_APELLIDO, E.EQUI_NOMBRE
FROM JUGADOR J
JOIN EQUIPO_JUGADOR EJ ON EJ.EQJU_JUGADOR = J.JUGA_DNI
JOIN EQUIPO E ON E.EQUI_CODIGO = EJ.EQJU_EQUIPO
JOIN JUGADOR_PARTIDO JP ON JP.JUPA_JUGADOR = J.JUGA_DNI
JOIN PARTIDO P ON P.PART_CODIGO = JP.JUPA_PARTIDO
WHERE P.PART_FECHA_TORNEO=1 AND P.PART_TORNEO=1
AND J.JUGA_DNI NOT IN 
	(SELECT JP.JUPA_JUGADOR
	FROM JUGADOR_PARTIDO JP
	WHERE JP.JUPA_PARTIDO =P.PART_CODIGO)