SELECT E.EQUI_NOMBRE
FROM EQUIPO E
JOIN PARTIDO P ON (P.PART_VISITANTE = E.EQUI_CODIGO)
WHERE 
	(P.PART_LOCAL IN 
				(SELECT EQUIPO.EQUI_CODIGO
				FROM EQUIPO JOIN EQUIPO_JUGADOR EJ ON EJ.EQJU_EQUIPO = EQUIPO.EQUI_CODIGO
				WHERE EJ.EQJU_JUGADOR=22880605)
	)
UNION
SELECT E.EQUI_NOMBRE
FROM EQUIPO E
JOIN PARTIDO P ON (P.PART_LOCAL = E.EQUI_CODIGO)
WHERE 
	(P.PART_VISITANTE IN 
				(SELECT EQUIPO.EQUI_CODIGO
				FROM EQUIPO JOIN EQUIPO_JUGADOR EJ ON EJ.EQJU_EQUIPO = EQUIPO.EQUI_CODIGO
				WHERE EJ.EQJU_JUGADOR=22880605)
	)