SELECT P.PART_CODIGO, T.TORN_CODIGO, E.EQUI_CODIGO, E.EQUI_NOMBRE, 
CASE WHEN	(
			SUM(CASE WHEN ((DP.DEPA_ACCION=1 AND DP.DEPA_EQUIPO=P.PART_LOCAL)
			OR (DP.DEPA_ACCION=10 AND DP.DEPA_EQUIPO=P.PART_VISITANTE))THEN 1 ELSE 0 END)
			) >
			(
			SUM(CASE WHEN ((DP.DEPA_ACCION=1 AND DP.DEPA_EQUIPO=P.PART_VISITANTE)
			OR (DP.DEPA_ACCION=10 AND DP.DEPA_EQUIPO=P.PART_LOCAL))
			THEN 1 ELSE 0 END)
			 ) THEN 3
			 
	WHEN	(
			SUM(CASE WHEN ((DP.DEPA_ACCION=1 AND DP.DEPA_EQUIPO=P.PART_LOCAL)
			OR (DP.DEPA_ACCION=10 AND DP.DEPA_EQUIPO=P.PART_VISITANTE))THEN 1 ELSE 0 END)
			) =
			(
			SUM(CASE WHEN ((DP.DEPA_ACCION=1 AND DP.DEPA_EQUIPO=P.PART_VISITANTE)
			OR (DP.DEPA_ACCION=10 AND DP.DEPA_EQUIPO=P.PART_LOCAL))
			THEN 1 ELSE 0 END)
			 ) THEN 1
	ELSE 0 END AS PUNTOS
FROM DETALLE_PARTIDO DP
JOIN PARTIDO P ON P.PART_CODIGO = DP.DEPA_PARTIDO
JOIN TORNEO T ON T.TORN_CODIGO = P.PART_TORNEO
JOIN EQUIPO E ON E.EQUI_CODIGO = P.PART_LOCAL
group by P.PART_CODIGO, T.TORN_CODIGO, E.EQUI_CODIGO, E.EQUI_NOMBRE
HAVING (
			SUM(CASE WHEN ((DP.DEPA_ACCION=1 AND DP.DEPA_EQUIPO=P.PART_LOCAL)
			OR (DP.DEPA_ACCION=10 AND DP.DEPA_EQUIPO=P.PART_VISITANTE))THEN 1 ELSE 0 END)
			) >=
			(
			SUM(CASE WHEN ((DP.DEPA_ACCION=1 AND DP.DEPA_EQUIPO=P.PART_VISITANTE)
			OR (DP.DEPA_ACCION=10 AND DP.DEPA_EQUIPO=P.PART_LOCAL))
			THEN 1 ELSE 0 END)
			 )
			 
UNION

SELECT P.PART_CODIGO, T.TORN_CODIGO, E.EQUI_CODIGO, E.EQUI_NOMBRE, 
CASE WHEN	(
			SUM(CASE WHEN ((DP.DEPA_ACCION=1 AND DP.DEPA_EQUIPO=P.PART_LOCAL)
			OR (DP.DEPA_ACCION=10 AND DP.DEPA_EQUIPO=P.PART_VISITANTE))THEN 1 ELSE 0 END)
			) <
			(
			SUM(CASE WHEN ((DP.DEPA_ACCION=1 AND DP.DEPA_EQUIPO=P.PART_VISITANTE)
			OR (DP.DEPA_ACCION=10 AND DP.DEPA_EQUIPO=P.PART_LOCAL))
			THEN 1 ELSE 0 END)
			 ) THEN 3
			 
	WHEN	(
			SUM(CASE WHEN ((DP.DEPA_ACCION=1 AND DP.DEPA_EQUIPO=P.PART_LOCAL)
			OR (DP.DEPA_ACCION=10 AND DP.DEPA_EQUIPO=P.PART_VISITANTE))THEN 1 ELSE 0 END)
			) =
			(
			SUM(CASE WHEN ((DP.DEPA_ACCION=1 AND DP.DEPA_EQUIPO=P.PART_VISITANTE)
			OR (DP.DEPA_ACCION=10 AND DP.DEPA_EQUIPO=P.PART_LOCAL))
			THEN 1 ELSE 0 END)
			 ) THEN 1
	ELSE 0 END AS PUNTOS
FROM DETALLE_PARTIDO DP
JOIN PARTIDO P ON P.PART_CODIGO = DP.DEPA_PARTIDO
JOIN TORNEO T ON T.TORN_CODIGO = P.PART_TORNEO
JOIN EQUIPO E ON E.EQUI_CODIGO = P.PART_VISITANTE
group by P.PART_CODIGO, T.TORN_CODIGO, E.EQUI_CODIGO, E.EQUI_NOMBRE
HAVING (
			SUM(CASE WHEN ((DP.DEPA_ACCION=1 AND DP.DEPA_EQUIPO=P.PART_LOCAL)
			OR (DP.DEPA_ACCION=10 AND DP.DEPA_EQUIPO=P.PART_VISITANTE))THEN 1 ELSE 0 END)
			) <=
			(
			SUM(CASE WHEN ((DP.DEPA_ACCION=1 AND DP.DEPA_EQUIPO=P.PART_VISITANTE)
			OR (DP.DEPA_ACCION=10 AND DP.DEPA_EQUIPO=P.PART_LOCAL))
			THEN 1 ELSE 0 END)
			 )