-- ---------------------------------------------------------------------------------------------------------------------------
/* 12) Escriba una consulta que retorne cuantos puntos obtuvo cada equipo en cada partido.
Se debe retornar:
1. Codigo de Torneo
2. Codigo de partido
3. Codigo de equipo
4. Nombre del equipo
5. Puntos que obtuvo
Solo se deben mostrar aquellas filas donde el equipo haya obtenido puntos (recuerde que se otorgan 3 puntos por partido ganado,
 1 por partido empatado y 0 por perdido) */
-- ---------------------------------------------------------------------------------------------------------------------------
SELECT
P.PART_TORNEO 'TORNEO',
P.PART_CODIGO 'PARTIDO', 
E.EQUI_CODIGO 'CODIGO EQUIPO', 
E.EQUI_NOMBRE 'EQUIPO',
CASE WHEN( /* CUANDO EL LOCAL GANA*/
(SUM(CASE WHEN((P.PART_LOCAL = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 1) OR (P.PART_VISITANTE = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 10)) THEN 1 ELSE 0 END) > 
SUM(CASE WHEN((P.PART_VISITANTE = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 1) OR (P.PART_LOCAL = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 10)) THEN 1 ELSE 0 END))) THEN 3
WHEN( /* CUANDO EMPATAN */
(SUM(CASE WHEN((P.PART_LOCAL = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 1) OR (P.PART_VISITANTE = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 10)) THEN 1 ELSE 0 END) = 
SUM(CASE WHEN((P.PART_VISITANTE = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 1) OR (P.PART_LOCAL = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 10)) THEN 1 ELSE 0 END))) THEN 1 
/* CUANDO EL LOCAL PIERDE */
ELSE 0 END 'PUNTOS'
 
FROM PARTIDO P
		 INNER JOIN DETALLE_PARTIDO DP ON P.PART_CODIGO = DP.DEPA_PARTIDO
		 INNER JOIN EQUIPO E ON E.EQUI_CODIGO = P.PART_LOCAL
		 
GROUP BY E.EQUI_CODIGO, E.EQUI_NOMBRE,P.PART_CODIGO,P.PART_TORNEO 

HAVING (
(SUM(CASE WHEN((P.PART_LOCAL = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 1) OR (P.PART_VISITANTE = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 10)) THEN 1 ELSE 0 END)) >= 
SUM(CASE WHEN((P.PART_VISITANTE = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 1) OR (P.PART_LOCAL = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 10)) THEN 1 ELSE 0 END)
       )
       
UNION

SELECT
P.PART_TORNEO 'TORNEO',
P.PART_CODIGO 'PARTIDO', 
E.EQUI_CODIGO 'CODIGO EQUIPO', 
E.EQUI_NOMBRE 'EQUIPO',
CASE WHEN( /* CUANDO EL VISITANTE GANA*/
(SUM(CASE WHEN((P.PART_LOCAL = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 1) OR (P.PART_VISITANTE = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 10)) THEN 1 ELSE 0 END) < 
SUM(CASE WHEN((P.PART_VISITANTE = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 1) OR (P.PART_LOCAL = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 10)) THEN 1 ELSE 0 END))) THEN 3
WHEN( /* CUANDO EMPATAN */
(SUM(CASE WHEN((P.PART_LOCAL = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 1) OR (P.PART_VISITANTE = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 10)) THEN 1 ELSE 0 END) = 
SUM(CASE WHEN((P.PART_VISITANTE = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 1) OR (P.PART_LOCAL = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 10)) THEN 1 ELSE 0 END))) THEN 1 
/* CUANDO EL LOCAL PIERDE */
ELSE 0 END 'PUNTOS'
 
FROM PARTIDO P
		 INNER JOIN DETALLE_PARTIDO DP ON P.PART_CODIGO = DP.DEPA_PARTIDO
		 INNER JOIN EQUIPO E ON E.EQUI_CODIGO = P.PART_VISITANTE
		 
GROUP BY E.EQUI_CODIGO, E.EQUI_NOMBRE,P.PART_CODIGO,P.PART_TORNEO
 
HAVING (
(SUM(CASE WHEN((P.PART_LOCAL = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 1) OR (P.PART_VISITANTE = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 10)) THEN 1 ELSE 0 END) <=
SUM(CASE WHEN((P.PART_VISITANTE = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 1) OR (P.PART_LOCAL = DP.DEPA_EQUIPO AND DP.DEPA_ACCION = 10)) THEN 1 ELSE 0 END))
       )