SELECT CONVERT(VARCHAR, PARTIDO.PART_FECHA_HORA) Fecha, eLocal.EQUI_NOMBRE Equipo_Local, eVisitante.EQUI_NOMBRE Equipo_Visitante,  ARBITRO.ARBI_APELLIDO + ', ' + ARBITRO.ARBI_NOMBRES Arbitro
FROM PARTIDO
JOIN TORNEO ON PARTIDO.PART_TORNEO = TORNEO.TORN_CODIGO AND TORNEO.TORN_DIVISION = 'A'
JOIN ARBITRO ON ARBITRO.ARBI_DNI = PARTIDO.PART_ARBITRO
JOIN EQUIPO eLocal ON PARTIDO.PART_LOCAL = eLocal.EQUI_CODIGO
JOIN EQUIPO eVisitante ON PARTIDO.PART_VISITANTE = eVisitante.EQUI_CODIGO
WHERE PARTIDO.PART_FECHA_TORNEO = 1
ORDER BY PARTIDO.PART_FECHA_HORA